### ISSUE TITLE
Some error after building with flatpak manifest

### ISSUE THREAD

**Issue by sabriunal** [nate-xyz/conjure#9]
Hi, I just installed Conjure using [this manifest](https://github.com/nate-xyz/conjure/blob/main/flatpak/io.github.nate_xyz.Conjure.json) and got this error after installation.

```
flatpak run io.github.nate_xyz.Conjure 
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/wand/api.py", line 154, in <module>
    libraries = load_library()
  File "/app/lib/python3.10/site-packages/wand/api.py", line 143, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/conjure", line 57, in <module>
    from conjure import main
  File "/app/share/conjure/conjure/main.py", line 26, in <module>
    from conjure.app import App
  File "/app/share/conjure/conjure/app.py", line 24, in <module>
    from conjure.window import Window
  File "/app/share/conjure/conjure/window.py", line 25, in <module>
    from conjure.views import ImageDropPage
  File "/app/share/conjure/conjure/views/__init__.py", line 1, in <module>
    from .image_drop_page import ImageDropPage
  File "/app/share/conjure/conjure/views/image_drop_page.py", line 5, in <module>
    from wand.display import display
  File "/app/lib/python3.10/site-packages/wand/display.py", line 31, in <module>
    from .image import Image
  File "/app/lib/python3.10/site-packages/wand/image.py", line 18, in <module>
    from . import assertions
  File "/app/lib/python3.10/site-packages/wand/assertions.py", line 155, in <module>
    from .color import Color  # noqa: E402
  File "/app/lib/python3.10/site-packages/wand/color.py", line 10, in <module>
    from .api import library
  File "/app/lib/python3.10/site-packages/wand/api.py", line 178, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html
```

**Comment by nate-xyz** [comment]
try this one, I need to update the manifest in this repo: https://github.com/flathub/io.github.nate_xyz.Conjure/blob/master/io.github.nate_xyz.Conjure.json

**Comment by sabriunal** [comment]
I can build with flathub manifest. Thanks.
